### ISSUE TITLE
[Proxy]: Room counter UX not intuitive #8836

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#143]
see https://github.com/RocketChat/Rocket.Chat/issues/8836

**Comment by mrsimpson** [comment]
`packages/rocketchat-ui-sidenav/client/roomList.html` -> counter

**Comment by mrsimpson** [comment]
seems not to be that easy to understand, where the count is coming from. Shortterm-workaround: hide it via custom css:
```css
.rooms-list__type .badge{
  	display: none
}
```
